# EDITAR AQUÍ: datos de los 10 vidrios
# Cuando cambies algo, guardas y corres: python scripts/actualizar_vidrios.py

VIDRIOS = [
    {
        "ref_code": "VP-001",
        "nombre": "Vidrio Templado 6mm",
        "tipo_vidrio": "Templado",
        "descripcion": "Vidrio templado de 6mm de espesor, ideal para divisiones de baño y puertas interiores. Alta resistencia al impacto y seguridad en caso de rotura.",
        "especificaciones": "Espesor: 6mm | Resistencia: 5 veces más que vidrio annealed | Acabado: Transparente | Uso: Interior",
        "imagen_principal": "/static/img/vidrios/VP-001.jpg",
        "activo": 1,
    },
    {
        "ref_code": "VP-002",
        "nombre": "Vidrio Laminado Acústico",
        "tipo_vidrio": "Laminado",
        "descripcion": "Vidrio laminado con intercalar acústico para reducción de ruido exterior. Perfecto para fachadas y ventanales en zonas urbanas.",
        "especificaciones": "Espesor total: 8.38mm (4+0.38+4) | Reducción acústica: 38dB | Seguridad: No se desprende al romper | Uso: Fachadas, ventanales",
        "imagen_principal": "/static/img/vidrios/VP-002.jpg",
        "activo": 1,
    },
    {
        "ref_code": "VP-003",
        "nombre": "Vidrio Reflectivo Solar",
        "tipo_vidrio": "Reflectivo",
        "descripcion": "Vidrio con capa reflectiva que reduce el calor solar en un 60%. Ideal para edificios con alta exposición al sol.",
        "especificaciones": "Espesor: 6mm | Factor solar: 0.40 | Reflexión exterior: 25% | Uso: Fachadas comerciales",
        "imagen_principal": "/static/img/vidrios/VP-003.jpg",
        "activo": 1,
    },
    {
        "ref_code": "VP-004",
        "nombre": "Vidrio Low-E 4mm",
        "tipo_vidrio": "Low-E",
        "descripcion": "Vidrio de baja emisividad que mejora la eficiencia energética del edificio. Mantiene el calor interior en invierno y lo repele en verano.",
        "especificaciones": "Espesor: 4mm | Emisividad: 0.03 | Transmisión luz: 80% | Uso: Ventanas residenciales",
        "imagen_principal": "/static/img/vidrios/VP-004.jpg",
        "activo": 1,
    },
    {
        "ref_code": "VP-005",
        "nombre": "Vidrio Espejado Bronce",
        "tipo_vidrio": "Espejado",
        "descripcion": "Vidrio espejado en tono bronce para fachadas con diseño arquitectónico distintivo. Privacidad total desde el exterior.",
        "especificaciones": "Espesor: 5mm | Color: Bronce | Reflexión: 55% | Uso: Fachadas, mobiliario",
        "imagen_principal": "/static/img/vidrios/VP-005.jpg",
        "activo": 1,
    },
    {
        "ref_code": "VP-006",
        "nombre": "Vidrio Grabado Ácido",
        "tipo_vidrio": "Decorativo",
        "descripcion": "Vidrio con acabado satinado por tratamiento ácido. Elegancia difusa que permite paso de luz con privacidad.",
        "especificaciones": "Espesor: 5mm | Acabado: Satinado unilateral | Transmisión luz: 85% | Uso: Divisiones, puertas",
        "imagen_principal": "/static/img/vidrios/VP-006.jpg",
        "activo": 1,
    },
    {
        "ref_code": "VP-007",
        "nombre": "Vidrio Templado Curvo",
        "tipo_vidrio": "Templado Curvo",
        "descripcion": "Vidrio templado con curvatura personalizada para proyectos arquitectónicos únicos. Resistencia estructural mantenida.",
        "especificaciones": "Espesor: 8-12mm | Curvatura: según diseño | Radio mínimo: 500mm | Uso: Barandas, fachadas curvas",
        "imagen_principal": "/static/img/vidrios/VP-007.jpg",
        "activo": 1,
    },
    {
        "ref_code": "VP-008",
        "nombre": "Vidrio Laminado Blindado",
        "tipo_vidrio": "Blindado",
        "descripcion": "Vidrio laminado de alta seguridad con capas de policarbonato. Resistencia a impactos balísticos nivel III-A.",
        "especificaciones": "Espesor total: 24mm | Nivel: III-A | Capas: 3 vidrios + 2 policarbonatos | Uso: Bancos, embajadas",
        "imagen_principal": "/static/img/vidrios/VP-008.jpg",
        "activo": 1,
    },
    {
        "ref_code": "VP-009",
        "nombre": "Vidrio Antihumedad para Baño",
        "tipo_vidrio": "Antihumedad",
        "descripcion": "Vidrio con tratamiento hidrofóbico que repele el agua y evita manchas de cal. Ideal para mamparas de ducha.",
        "especificaciones": "Espesor: 6mm | Tratamiento: Nanocapa hidrofóbica | Garantía: 5 años | Uso: Mamparas, divisiones húmedas",
        "imagen_principal": "/static/img/vidrios/VP-009.jpg",
        "activo": 1,
    },
    {
        "ref_code": "VP-010",
        "nombre": "Vidrio Serigrafiado Decorativo",
        "tipo_vidrio": "Serigrafiado",
        "descripcion": "Vidrio con diseños serigrafiados en cerámica cocida al fuego. Personalizable con logos o patrones arquitectónicos.",
        "especificaciones": "Espesor: 6-10mm | Diseño: Personalizable | Durabilidad: Permanente | Uso: Fachadas, divisiones corporativas",
        "imagen_principal": "/static/img/vidrios/VP-010.jpg",
        "activo": 1,
    },
]