# Archivo maestro: 36 vidrios originales + 41 vidrios nuevos = 77 en total.
# Las "especificaciones" marcadas como "[completar]" necesitan el dato
# técnico real (espesor, composición, factor solar, etc.) para no
# inventar cifras que le lleguen a un cliente.
#
# Cuando termines de editar, corres el script que sube esto a la
# base de datos (te lo doy después de que confirmes que este archivo
# está bien).

VIDRIOS = [
    # ============================================================
    # 36 VIDRIOS ORIGINALES
    # ============================================================
    {
        "ref_code": "VP-001",
        "nombre": "Vidrio Templado 6mm",
        "tipo_vidrio": "Templado",
        "descripcion": "Vidrio templado de 6mm de espesor, ideal para divisiones de baño y puertas interiores. Alta resistencia al impacto y seguridad en caso de rotura.",
        "especificaciones": "Espesor: 6mm | Resistencia: 5 veces más que vidrio annealed | Acabado: Transparente | Uso: Interior",
        "imagen_principal": "/static/img/vidrios/VP-001.jpg",
        "categoria": "design",
        "activo": 1,
    },
    {
        "ref_code": "VP-002",
        "nombre": "Vidrio Laminado Acústico",
        "tipo_vidrio": "Laminado",
        "descripcion": "Vidrio laminado con intercalar acústico para reducción de ruido exterior. Perfecto para fachadas y ventanales en zonas urbanas.",
        "especificaciones": "Espesor total: 8.38mm (4+0.38+4) | Reducción acústica: 38dB | Seguridad: No se desprende al romper | Uso: Fachadas, ventanales",
        "imagen_principal": "/static/img/vidrios/VP-002.jpg",
        "categoria": "design",
        "activo": 1,
    },
    {
        "ref_code": "VP-003",
        "nombre": "Vidrio Reflectivo Solar",
        "tipo_vidrio": "Reflectivo",
        "descripcion": "Vidrio con capa reflectiva que reduce el calor solar en un 60%. Ideal para edificios con alta exposición al sol.",
        "especificaciones": "Espesor: 6mm | Factor solar: 0.40 | Reflexión exterior: 25% | Uso: Fachadas comerciales",
        "imagen_principal": "/static/img/vidrios/VP-003.jpg",
        "categoria": "design",
        "activo": 1,
    },
    {
        "ref_code": "VP-004",
        "nombre": "Vidrio Low-E 4mm",
        "tipo_vidrio": "Low-E",
        "descripcion": "Vidrio de baja emisividad que mejora la eficiencia energética del edificio. Mantiene el calor interior en invierno y lo repele en verano.",
        "especificaciones": "Espesor: 4mm | Emisividad: 0.03 | Transmisión luz: 80% | Uso: Ventanas residenciales",
        "imagen_principal": "/static/img/vidrios/VP-004.jpg",
        "categoria": "design",
        "activo": 1,
    },
    {
        "ref_code": "VP-005",
        "nombre": "Vidrio Espejado Bronce",
        "tipo_vidrio": "Espejado",
        "descripcion": "Vidrio espejado en tono bronce para fachadas con diseño arquitectónico distintivo. Privacidad total desde el exterior.",
        "especificaciones": "Espesor: 5mm | Color: Bronce | Reflexión: 55% | Uso: Fachadas, mobiliario",
        "imagen_principal": "/static/img/vidrios/VP-005.jpg",
        "categoria": "design",
        "activo": 1,
    },
    {
        "ref_code": "VP-006",
        "nombre": "Vidrio Grabado Ácido",
        "tipo_vidrio": "Decorativo",
        "descripcion": "Vidrio con acabado satinado por tratamiento ácido. Elegancia difusa que permite paso de luz con privacidad.",
        "especificaciones": "Espesor: 5mm | Acabado: Satinado unilateral | Transmisión luz: 85% | Uso: Divisiones, puertas",
        "imagen_principal": "/static/img/vidrios/VP-006.jpg",
        "categoria": "design",
        "activo": 1,
    },
    {
        "ref_code": "VP-007",
        "nombre": "Vidrio Templado Curvo",
        "tipo_vidrio": "Templado Curvo",
        "descripcion": "Vidrio templado con curvatura personalizada para proyectos arquitectónicos únicos. Resistencia estructural mantenida.",
        "especificaciones": "Espesor: 8-12mm | Curvatura: según diseño | Radio mínimo: 500mm | Uso: Barandas, fachadas curvas",
        "imagen_principal": "/static/img/vidrios/VP-007.jpg",
        "categoria": "confort",
        "activo": 1,
    },
    {
        "ref_code": "VP-008",
        "nombre": "Vidrio Laminado Blindado",
        "tipo_vidrio": "Blindado",
        "descripcion": "Vidrio laminado de alta seguridad con capas de policarbonato. Resistencia a impactos balísticos nivel III-A.",
        "especificaciones": "Espesor total: 24mm | Nivel: III-A | Capas: 3 vidrios + 2 policarbonatos | Uso: Bancos, embajadas",
        "imagen_principal": "/static/img/vidrios/VP-008.jpg",
        "categoria": "confort",
        "activo": 1,
    },
    {
        "ref_code": "VP-009",
        "nombre": "Vidrio Antihumedad para Baño",
        "tipo_vidrio": "Antihumedad",
        "descripcion": "Vidrio con tratamiento hidrofóbico que repele el agua y evita manchas de cal. Ideal para mamparas de ducha.",
        "especificaciones": "Espesor: 6mm | Tratamiento: Nanocapa hidrofóbica | Garantía: 5 años | Uso: Mamparas, divisiones húmedas",
        "imagen_principal": "/static/img/vidrios/VP-009.jpg",
        "categoria": "confort",
        "activo": 1,
    },
    {
        "ref_code": "VP-010",
        "nombre": "Vidrio Serigrafiado Decorativo",
        "tipo_vidrio": "Serigrafiado",
        "descripcion": "Vidrio con diseños serigrafiados en cerámica cocida al fuego. Personalizable con logos o patrones arquitectónicos.",
        "especificaciones": "Espesor: 6-10mm | Diseño: Personalizable | Durabilidad: Permanente | Uso: Fachadas, divisiones corporativas",
        "imagen_principal": "/static/img/vidrios/VP-010.jpg",
        "categoria": "confort",
        "activo": 1,
    },
    {
        "ref_code": "VP-011",
        "nombre": "Vidrio Laminado Decorativo Confort",
        "tipo_vidrio": "Laminado",
        "descripcion": "Vidrio laminado pensado para espacios de confort residencial.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-011.jpg",
        "categoria": "confort",
        "activo": 1,
    },
    {
        "ref_code": "VP-012",
        "nombre": "Vidrio Templado Térmico Confort",
        "tipo_vidrio": "Templado",
        "descripcion": "Vidrio templado con aislamiento térmico para interiores.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-012.jpg",
        "categoria": "confort",
        "activo": 1,
    },
    {
        "ref_code": "VP-013",
        "nombre": "Vidrio DVH Refrigeración Comercial",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético para cámaras de refrigeración.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-013.jpg",
        "categoria": "refrigeracion",
        "activo": 1,
    },
    {
        "ref_code": "VP-014",
        "nombre": "Vidrio Bajo Emisivo Refrigeración",
        "tipo_vidrio": "Low-E",
        "descripcion": "Control térmico para vitrinas refrigeradas.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-014.jpg",
        "categoria": "refrigeracion",
        "activo": 1,
    },
    {
        "ref_code": "VP-015",
        "nombre": "Vidrio Antiempañante Refrigeración",
        "tipo_vidrio": "Antiempañante",
        "descripcion": "Evita condensación en cuartos fríos y neveras.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-015.jpg",
        "categoria": "refrigeracion",
        "activo": 1,
    },
    {
        "ref_code": "VP-016",
        "nombre": "Vidrio Termopanel Refrigeración",
        "tipo_vidrio": "Termopanel",
        "descripcion": "Aislamiento para exhibidores refrigerados.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-016.jpg",
        "categoria": "refrigeracion",
        "activo": 1,
    },
    {
        "ref_code": "VP-017",
        "nombre": "Vidrio Triple Panel Refrigeración",
        "tipo_vidrio": "Triple Panel",
        "descripcion": "Máximo aislamiento térmico para cuartos fríos.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-017.jpg",
        "categoria": "refrigeracion",
        "activo": 1,
    },
    {
        "ref_code": "VP-018",
        "nombre": "Vidrio Curvo Refrigeración",
        "tipo_vidrio": "Curvo",
        "descripcion": "Vidrio curvo para vitrinas de refrigeración.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-018.jpg",
        "categoria": "refrigeracion",
        "activo": 1,
    },
    {
        "ref_code": "VP-019",
        "nombre": "Vidrio SolarCool Control Solar",
        "tipo_vidrio": "Control Solar",
        "descripcion": "Reduce ganancia térmica en fachadas.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-019.jpg",
        "categoria": "control-solar",
        "activo": 1,
    },
    {
        "ref_code": "VP-020",
        "nombre": "Vidrio Reflectivo Control Solar",
        "tipo_vidrio": "Reflectivo",
        "descripcion": "Alta reflectividad para control de radiación solar.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-020.jpg",
        "categoria": "control-solar",
        "activo": 1,
    },
    {
        "ref_code": "VP-021",
        "nombre": "Vidrio Low-E Control Solar",
        "tipo_vidrio": "Low-E",
        "descripcion": "Baja emisividad para eficiencia energética.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-021.jpg",
        "categoria": "control-solar",
        "activo": 1,
    },
    {
        "ref_code": "VP-022",
        "nombre": "Vidrio Gris Control Solar",
        "tipo_vidrio": "Gris Solar",
        "descripcion": "Tono gris para reducción de luminosidad.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-022.jpg",
        "categoria": "control-solar",
        "activo": 1,
    },
    {
        "ref_code": "VP-023",
        "nombre": "Vidrio Bronce Control Solar",
        "tipo_vidrio": "Bronce Solar",
        "descripcion": "Tono bronce con control de calor.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-023.jpg",
        "categoria": "control-solar",
        "activo": 1,
    },
    {
        "ref_code": "VP-024",
        "nombre": "Vidrio Azul Control Solar",
        "tipo_vidrio": "Azul Solar",
        "descripcion": "Tono azul con filtro solar.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-024.jpg",
        "categoria": "control-solar",
        "activo": 1,
    },
    {
        "ref_code": "VP-025",
        "nombre": "Vidrio Templado Seguridad HS",
        "tipo_vidrio": "Templado HS",
        "descripcion": "Vidrio de seguridad termoendurecido.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-025.jpg",
        "categoria": "seguridad",
        "activo": 1,
    },
    {
        "ref_code": "VP-026",
        "nombre": "Vidrio Laminado Seguridad",
        "tipo_vidrio": "Laminado",
        "descripcion": "Laminado de seguridad anti-impacto.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-026.jpg",
        "categoria": "seguridad",
        "activo": 1,
    },
    {
        "ref_code": "VP-027",
        "nombre": "Vidrio Blindado Seguridad",
        "tipo_vidrio": "Blindado",
        "descripcion": "Protección balística para fachadas críticas.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-027.jpg",
        "categoria": "seguridad",
        "activo": 1,
    },
    {
        "ref_code": "VP-028",
        "nombre": "Vidrio Antivandálico Seguridad",
        "tipo_vidrio": "Antivandálico",
        "descripcion": "Resistente a impactos y vandalismo.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-028.jpg",
        "categoria": "seguridad",
        "activo": 1,
    },
    {
        "ref_code": "VP-029",
        "nombre": "Vidrio Templado Seguridad Piso",
        "tipo_vidrio": "Templado Piso",
        "descripcion": "Vidrio de seguridad para pisos.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-029.jpg",
        "categoria": "seguridad",
        "activo": 1,
    },
    {
        "ref_code": "VP-030",
        "nombre": "Vidrio Laminado Seguridad Baranda",
        "tipo_vidrio": "Laminado Baranda",
        "descripcion": "Para barandas y escaleras.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-030.jpg",
        "categoria": "seguridad",
        "activo": 1,
    },
    {
        "ref_code": "VP-031",
        "nombre": "Vidrio Estructural Alto Desempeño",
        "tipo_vidrio": "Estructural",
        "descripcion": "Vidrio para fachadas estructurales de gran formato.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-031.jpg",
        "categoria": "alto-desempeno",
        "activo": 1,
    },
    {
        "ref_code": "VP-032",
        "nombre": "Vidrio Curvo Alto Desempeño",
        "tipo_vidrio": "Curvo",
        "descripcion": "Vidrio curvo para arquitectura de alto desempeño.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-032.jpg",
        "categoria": "alto-desempeno",
        "activo": 1,
    },
    {
        "ref_code": "VP-033",
        "nombre": "Vidrio DVH Alto Desempeño",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado para fachadas de alto rendimiento.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-033.jpg",
        "categoria": "alto-desempeno",
        "activo": 1,
    },
    {
        "ref_code": "VP-034",
        "nombre": "Vidrio Acústico Alto Desempeño",
        "tipo_vidrio": "Acústico",
        "descripcion": "Control acústico para edificios corporativos.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-034.jpg",
        "categoria": "alto-desempeno",
        "activo": 1,
    },
    {
        "ref_code": "VP-035",
        "nombre": "Vidrio Estructural Fachada",
        "tipo_vidrio": "Estructural",
        "descripcion": "Sistema estructural de fachada continua.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-035.jpg",
        "categoria": "alto-desempeno",
        "activo": 1,
    },
    {
        "ref_code": "VP-036",
        "nombre": "Vidrio Panel Alto Desempeño",
        "tipo_vidrio": "Panel",
        "descripcion": "Panel de alto desempeño térmico-acústico.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-036.jpg",
        "categoria": "alto-desempeno",
        "activo": 1,
    },

    # ============================================================
    # 41 VIDRIOS NUEVOS (VP-037 a VP-077)
    # ============================================================

    # ---------- CONFORT ----------
    {
        "ref_code": "VP-037", "nombre": "DVH Confort Negro", "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono negro, pensado para espacios de confort residencial con estética elegante y sobria.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-037.jpg", "categoria": "confort", "activo": 1,
    },
    {
        "ref_code": "VP-038", "nombre": "DVH Confort Blanco", "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono blanco, ideal para espacios luminosos que buscan confort térmico y acústico.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-038.jpg", "categoria": "confort", "activo": 1,
    },
    {
        "ref_code": "VP-039", "nombre": "DVH Confort Amarillo", "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono amarillo, para proyectos que buscan un toque de color junto al aislamiento propio del DVH.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-039.jpg", "categoria": "confort", "activo": 1,
    },
    {
        "ref_code": "VP-040", "nombre": "DVH Confort Azul Océano", "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono azul océano, aporta frescura visual manteniendo el confort térmico del espacio.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-040.jpg", "categoria": "confort", "activo": 1,
    },
    {
        "ref_code": "VP-041", "nombre": "DVH Confort Median Blue", "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono Median Blue, combina diseño contemporáneo con desempeño térmico.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-041.jpg", "categoria": "confort", "activo": 1,
    },
    {
        "ref_code": "VP-042", "nombre": "DVH Arquitectonico Violeta", "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono violeta, para fachadas y espacios con identidad visual distintiva.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-042.jpg", "categoria": "arquitectonico", "activo": 1,
    },
    {
        "ref_code": "VP-044", "nombre": "DVH Confort Negro", "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono negro, pensado para espacios de confort residencial con estética elegante y sobria.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-044.jpg", "categoria": "confort", "activo": 1,
    },
    {
        "ref_code": "VP-045", "nombre": "DVH Confort Incoloro", "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético incoloro, para máxima transparencia sin sacrificar el confort térmico y acústico.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-045.jpg", "categoria": "confort", "activo": 1,
    },
    {
        "ref_code": "VP-046", "nombre": "DVH Arquitectonico Violeta", "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono violeta, para fachadas y espacios con identidad visual distintiva.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-046.jpg", "categoria": "arquitectonico", "activo": 1,
    },
    {
        "ref_code": "VP-047", "nombre": "DVH Arquitectonico Verde", "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono verde, aporta un aire natural al espacio sin perder desempeño térmico.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-047.jpg", "categoria": "arquitectonico", "activo": 1,
    },
    {
        "ref_code": "VP-049", "nombre": "DVH Confort Design", "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético de línea Confort con acabado tipo Design, combinando estética y desempeño térmico.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-049.jpg", "categoria": "confort", "activo": 1,
    },
    {
        "ref_code": "VP-050", "nombre": "DVH Confort Design", "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético de línea Confort con acabado tipo Design, combinando estética y desempeño térmico.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-050.jpg", "categoria": "confort", "activo": 1,
    },
    {
        "ref_code": "VP-051", "nombre": "DVH Confort Incoloro", "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético incoloro, para máxima transparencia sin sacrificar el confort térmico y acústico.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-051.jpg", "categoria": "confort", "activo": 1,
    },
    {
        "ref_code": "VP-052", "nombre": "DVH Confort Gris Median", "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono gris Median, aporta sobriedad y control de luminosidad al espacio.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-052.jpg", "categoria": "confort", "activo": 1,
    },
    {
        "ref_code": "VP-056", "nombre": "DVH Arquitectonico Verde", "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono verde, aporta un aire natural al espacio sin perder desempeño térmico.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-056.jpg", "categoria": "arquitectonico", "activo": 1,
    },
    {
        "ref_code": "VP-057", "nombre": "DVH Arquitectonico Rojo Dip", "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono rojo Dip, para proyectos que buscan un acento de color audaz.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-057.jpg", "categoria": "arquitectonico", "activo": 1,
    },
    {
        "ref_code": "VP-058", "nombre": "DVH Confort Blanco", "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono blanco, ideal para espacios luminosos que buscan confort térmico y acústico.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-058.jpg", "categoria": "confort", "activo": 1,
    },
    {
        "ref_code": "VP-059", "nombre": "DVH Confort Gris Asahi", "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono gris Asahi, combina elegancia y control de luminosidad.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-059.jpg", "categoria": "confort", "activo": 1,
    },
    {
        "ref_code": "VP-060", "nombre": "DVH Confort Hielo", "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono hielo, aporta luminosidad suave y estética contemporánea.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-060.jpg", "categoria": "confort", "activo": 1,
    },
    {
        "ref_code": "VP-067", "nombre": "DVH Arquitectonico Verde", "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono verde, aporta un aire natural al espacio sin perder desempeño térmico.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-067.jpg", "categoria": "arquitectonico", "activo": 1,
    },
    {
        "ref_code": "VP-069", "nombre": "DVH Confort Blanco", "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono blanco, ideal para espacios luminosos que buscan confort térmico y acústico.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-069.jpg", "categoria": "confort", "activo": 1,
    },
    {
        "ref_code": "VP-070", "nombre": "DVH Arquitectonico Rojo Dip", "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono rojo Dip, para proyectos que buscan un acento de color audaz.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-070.jpg", "categoria": "arquitectonico", "activo": 1,
    },
    {
        "ref_code": "VP-071", "nombre": "DVH Confort Azul Median Blue", "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono azul Median Blue, combina diseño contemporáneo con desempeño térmico.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-071.jpg", "categoria": "confort", "activo": 1,
    },
    {
        "ref_code": "VP-075", "nombre": "DVH Confort Blanco", "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono blanco, ideal para espacios luminosos que buscan confort térmico y acústico.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-075.jpg", "categoria": "confort", "activo": 1,
    },
    {
        "ref_code": "VP-076", "nombre": "DVH Confort Gris Asahi", "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono gris Asahi, combina elegancia y control de luminosidad.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-076.jpg", "categoria": "confort", "activo": 1,
    },
    {
        "ref_code": "VP-077", "nombre": "DVH Confort Incoloro", "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético incoloro, para máxima transparencia sin sacrificar el confort térmico y acústico.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-077.jpg", "categoria": "confort", "activo": 1,
    },

    # ---------- CONTROL SOLAR ----------
    {
        "ref_code": "VP-043", "nombre": "DVH Control Solar ST-136", "tipo_vidrio": "DVH Control Solar",
        "descripcion": "Doble vidriado hermético con vidrio de control solar ST-136, reduce la ganancia de calor manteniendo buena claridad.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-043.jpg", "categoria": "control-solar", "activo": 1,
    },
    {
        "ref_code": "VP-053", "nombre": "DVH Control Solar ST-150", "tipo_vidrio": "DVH Control Solar",
        "descripcion": "Doble vidriado hermético con vidrio de control solar ST-150, ideal para fachadas con alta exposición solar.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-053.jpg", "categoria": "control-solar", "activo": 1,
    },
    {
        "ref_code": "VP-054", "nombre": "DVH Control Solar ST-120", "tipo_vidrio": "DVH Control Solar",
        "descripcion": "Doble vidriado hermético con vidrio de control solar ST-120, equilibra transmisión de luz y control térmico.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-054.jpg", "categoria": "control-solar", "activo": 1,
    },
    {
        "ref_code": "VP-061", "nombre": "DVH Control Solar ST-167", "tipo_vidrio": "DVH Control Solar",
        "descripcion": "Doble vidriado hermético con vidrio de control solar ST-167, reduce la ganancia de calor solar manteniendo claridad.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-061.jpg", "categoria": "control-solar", "activo": 1,
    },
    {
        "ref_code": "VP-062", "nombre": "DVH Control Solar ST-150", "tipo_vidrio": "DVH Control Solar",
        "descripcion": "Doble vidriado hermético con vidrio de control solar ST-150, ideal para fachadas con alta exposición solar.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-062.jpg", "categoria": "control-solar", "activo": 1,
    },
    {
        "ref_code": "VP-063", "nombre": "DVH Control Solar ST-150", "tipo_vidrio": "DVH Control Solar",
        "descripcion": "Doble vidriado hermético con vidrio de control solar ST-150, ideal para fachadas con alta exposición solar.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-063.jpg", "categoria": "control-solar", "activo": 1,
    },
    {
        "ref_code": "VP-065", "nombre": "DVH Control Solar ST-150", "tipo_vidrio": "DVH Control Solar",
        "descripcion": "Doble vidriado hermético con vidrio de control solar ST-150, ideal para fachadas con alta exposición solar.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-065.jpg", "categoria": "control-solar", "activo": 1,
    },
    {
        "ref_code": "VP-068", "nombre": "DVH Control Solar ST-136", "tipo_vidrio": "DVH Control Solar",
        "descripcion": "Doble vidriado hermético con vidrio de control solar ST-136, reduce la ganancia de calor manteniendo buena claridad.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-068.jpg", "categoria": "control-solar", "activo": 1,
    },
    {
        "ref_code": "VP-072", "nombre": "DVH Control Solar ST-120", "tipo_vidrio": "DVH Control Solar",
        "descripcion": "Doble vidriado hermético con vidrio de control solar ST-120, equilibra transmisión de luz y control térmico.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-072.jpg", "categoria": "control-solar", "activo": 1,
    },

    # ---------- DESIGN ----------
    {
        "ref_code": "VP-048", "nombre": "DVH Design Naranja Tangerine", "tipo_vidrio": "DVH Design",
        "descripcion": "Doble vidriado hermético en tono naranja Tangerine, línea Design con acabado de alto impacto visual.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-048.jpg", "categoria": "design", "activo": 1,
    },
    {
        "ref_code": "VP-064", "nombre": "DVH Design Naranja Tangerine", "tipo_vidrio": "DVH Design",
        "descripcion": "Doble vidriado hermético en tono naranja Tangerine, línea Design con acabado de alto impacto visual.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-064.jpg", "categoria": "design", "activo": 1,
    },

    # ---------- ALTO DESEMPEÑO ----------
    {
        "ref_code": "VP-055", "nombre": "DVH Alto Desempeño KNT-155", "tipo_vidrio": "DVH Alto Desempeño",
        "descripcion": "Doble vidriado hermético con vidrio KNT-155, alto desempeño térmico y acústico para fachadas exigentes.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-055.jpg", "categoria": "alto-desempeno", "activo": 1,
    },
    {
        "ref_code": "VP-066", "nombre": "DVH Alto Desempeño Planitherm", "tipo_vidrio": "DVH Alto Desempeño",
        "descripcion": "Doble vidriado hermético con vidrio Planitherm, máximo aislamiento térmico para proyectos de alto desempeño.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-066.jpg", "categoria": "alto-desempeno", "activo": 1,
    },
    {
        "ref_code": "VP-073", "nombre": "DVH Alto Desempeño", "tipo_vidrio": "DVH Alto Desempeño",
        "descripcion": "Doble vidriado hermético de línea Alto Desempeño, pensado para fachadas de gran exigencia térmica y estructural.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-073.jpg", "categoria": "alto-desempeno", "activo": 1,
    },
    {
        "ref_code": "VP-074", "nombre": "DVH Alto Desempeño KNT-155", "tipo_vidrio": "DVH Alto Desempeño",
        "descripcion": "Doble vidriado hermético con vidrio KNT-155, alto desempeño térmico y acústico para fachadas exigentes.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-074.jpg", "categoria": "alto-desempeno", "activo": 1,
    },
]