# Exportado automaticamente desde la base de datos real.
# Total de vidrios encontrados: 41

VIDRIOS = [
    {
        "ref_code": "VP-001",
        "nombre": "DVH Confort Negro",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono negro, pensado para espacios de confort residencial con estética elegante y sobria.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-037.jpg",
        "categoria": "confort",
        "activo": 1,
    },
    {
        "ref_code": "VP-002",
        "nombre": "DVH Confort Blanco",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono blanco, ideal para espacios luminosos que buscan confort térmico y acústico.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-038.jpg",
        "categoria": "confort",
        "activo": 1,
    },
    {
        "ref_code": "VP-003",
        "nombre": "DVH Confort Amarillo",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono amarillo, para proyectos que buscan un toque de color junto al aislamiento propio del DVH.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-039.jpg",
        "categoria": "confort",
        "activo": 1,
    },
    {
        "ref_code": "VP-004",
        "nombre": "DVH Confort Azul Océano",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono azul océano, aporta frescura visual manteniendo el confort térmico del espacio.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-040.jpg",
        "categoria": "confort",
        "activo": 1,
    },
    {
        "ref_code": "VP-005",
        "nombre": "DVH Confort Median Blue",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono Median Blue, combina diseño contemporáneo con desempeño térmico.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-041.jpg",
        "categoria": "confort",
        "activo": 1,
    },
    {
        "ref_code": "VP-006",
        "nombre": "DVH Arquitectonico Violeta",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono violeta, para fachadas y espacios con identidad visual distintiva.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-042.jpg",
        "categoria": "arquitectonico",
        "activo": 1,
    },
    {
        "ref_code": "VP-007",
        "nombre": "DVH Confort Gris Medium",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono gris Medium, aporta sobriedad y control de luminosidad manteniendo el confort térmico y acústico del espacio.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-043.jpg",
        "categoria": "confort",
        "activo": 1,
    },
    {
        "ref_code": "VP-008",
        "nombre": "DVH Confort Gris Asahi",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono gris Asahi, combina elegancia y control de luminosidad para espacios de confort residencial.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-044.jpg",
        "categoria": "confort",
        "activo": 1,
    },
    {
        "ref_code": "VP-009",
        "nombre": "DVH Confort Gris Medium",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono gris Medium, aporta sobriedad y control de luminosidad sin sacrificar el confort térmico y acústico.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-045.jpg",
        "categoria": "confort",
        "activo": 1,
    },
    {
        "ref_code": "VP-010",
        "nombre": "DVH Arquitectonico Violeta",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono violeta, para fachadas y espacios con identidad visual distintiva.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-046.jpg",
        "categoria": "arquitectonico",
        "activo": 1,
    },
    {
        "ref_code": "VP-011",
        "nombre": "DVH Arquitectonico Verde",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono verde, aporta un aire natural al espacio sin perder desempeño térmico.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-047.jpg",
        "categoria": "arquitectonico",
        "activo": 1,
    },
    {
        "ref_code": "VP-012",
        "nombre": "DVH Design Naranja Tangerine",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono naranja Tangerine, línea Design con acabado de alto impacto visual.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-048.jpg",
        "categoria": "design",
        "activo": 1,
    },
    {
        "ref_code": "VP-013",
        "nombre": "DVH Confort SPVP Verde",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono verde con intercalar SPVP, combina estética natural y desempeño térmico para espacios de confort.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-049.jpg",
        "categoria": "confort",
        "activo": 1,
    },
    {
        "ref_code": "VP-014",
        "nombre": "DVH Confort SPVP Verde",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono verde con intercalar SPVP, combina estética natural y desempeño térmico para espacios de confort.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-050.jpg",
        "categoria": "confort",
        "activo": 1,
    },
    {
        "ref_code": "VP-015",
        "nombre": "DVH Confort Incoloro",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético incoloro, para máxima transparencia sin sacrificar el confort térmico y acústico.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-051.jpg",
        "categoria": "confort",
        "activo": 1,
    },
    {
        "ref_code": "VP-016",
        "nombre": "DVH Confort Gris Median",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono gris Median, aporta sobriedad y control de luminosidad al espacio.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-052.jpg",
        "categoria": "confort",
        "activo": 1,
    },
    {
        "ref_code": "VP-017",
        "nombre": "DVH Control Solar ST-150",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético con vidrio de control solar ST-150, ideal para fachadas con alta exposición solar.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-053.jpg",
        "categoria": "control-solar",
        "activo": 1,
    },
    {
        "ref_code": "VP-018",
        "nombre": "DVH Control Solar STB-120",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético con vidrio de control solar STB-120, equilibra transmisión de luz y control térmico.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-054.jpg",
        "categoria": "control-solar",
        "activo": 1,
    },
    {
        "ref_code": "VP-019",
        "nombre": "DVH Alto Desempeño KNT-155",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético con vidrio KNT-155, alto desempeño térmico y acústico para fachadas exigentes.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-055.jpg",
        "categoria": "alto-desempeno",
        "activo": 1,
    },
    {
        "ref_code": "VP-020",
        "nombre": "DVH Arquitectonico Verde",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono verde, aporta un aire natural al espacio sin perder desempeño térmico.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-056.jpg",
        "categoria": "arquitectonico",
        "activo": 1,
    },
    {
        "ref_code": "VP-021",
        "nombre": "DVH Arquitectonico Rojo Dip",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono rojo Dip, para proyectos que buscan un acento de color audaz.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-057.jpg",
        "categoria": "arquitectonico",
        "activo": 1,
    },
    {
        "ref_code": "VP-022",
        "nombre": "DVH Confort Bronce",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono bronce, aporta calidez y privacidad visual manteniendo el confort térmico y acústico del espacio.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-058.jpg",
        "categoria": "confort",
        "activo": 1,
    },
    {
        "ref_code": "VP-023",
        "nombre": "DVH Confort Gris Asahi",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono gris Asahi, combina elegancia y control de luminosidad.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-059.jpg",
        "categoria": "confort",
        "activo": 1,
    },
    {
        "ref_code": "VP-024",
        "nombre": "DVH Confort Hielo",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono hielo, aporta luminosidad suave y estética contemporánea.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-060.jpg",
        "categoria": "confort",
        "activo": 1,
    },
    {
        "ref_code": "VP-025",
        "nombre": "DVH Control Solar ST-167",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético con vidrio de control solar ST-167, reduce la ganancia de calor solar manteniendo claridad.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-061.jpg",
        "categoria": "control-solar",
        "activo": 1,
    },
    {
        "ref_code": "VP-026",
        "nombre": "DVH Control Solar ST-150 Grendo",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético con vidrio de control solar ST-150 Grendo, ideal para fachadas con alta exposición solar.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-062.jpg",
        "categoria": "control-solar",
        "activo": 1,
    },
    {
        "ref_code": "VP-027",
        "nombre": "DVH Control Solar KNT-155",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético con vidrio de control solar KNT-155, alto desempeño térmico y acústico para fachadas exigentes.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-063.jpg",
        "categoria": "control-solar",
        "activo": 1,
    },
    {
        "ref_code": "VP-028",
        "nombre": "DVH Design Naranja Tangerine",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono naranja Tangerine, línea Design con acabado de alto impacto visual.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-064.jpg",
        "categoria": "design",
        "activo": 1,
    },
    {
        "ref_code": "VP-029",
        "nombre": "DVH Control Solar ST-150",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético con vidrio de control solar ST-150, ideal para fachadas con alta exposición solar.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-065.jpg",
        "categoria": "control-solar",
        "activo": 1,
    },
    {
        "ref_code": "VP-030",
        "nombre": "DVH Alto Desempeño ST-167",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético con vidrio de control solar ST-167, reduce la ganancia de calor solar manteniendo claridad y desempeño.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-066.jpg",
        "categoria": "alto-desempeno",
        "activo": 1,
    },
    {
        "ref_code": "VP-031",
        "nombre": "DVH Arquitectonico Verde",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono verde, aporta un aire natural al espacio sin perder desempeño térmico.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-067.jpg",
        "categoria": "arquitectonico",
        "activo": 1,
    },
    {
        "ref_code": "VP-032",
        "nombre": "DVH Control Solar ST-150",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético con vidrio de control solar ST-150, ideal para fachadas con alta exposición solar.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-068.jpg",
        "categoria": "control-solar",
        "activo": 1,
    },
    {
        "ref_code": "VP-033",
        "nombre": "DVH Confort Blanco",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono blanco, ideal para espacios luminosos que buscan confort térmico y acústico.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-069.jpg",
        "categoria": "confort",
        "activo": 1,
    },
    {
        "ref_code": "VP-034",
        "nombre": "DVH Arquitectonico Rojo Dip",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono rojo Dip, para proyectos que buscan un acento de color audaz.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-070.jpg",
        "categoria": "arquitectonico",
        "activo": 1,
    },
    {
        "ref_code": "VP-035",
        "nombre": "DVH Confort Azul Median Blue",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono azul Median Blue, combina diseño contemporáneo con desempeño térmico.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-071.jpg",
        "categoria": "confort",
        "activo": 1,
    },
    {
        "ref_code": "VP-036",
        "nombre": "DVH Control Solar ST-120",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético con vidrio de control solar ST-120, equilibra transmisión de luz y control térmico.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-072.jpg",
        "categoria": "control-solar",
        "activo": 1,
    },
    {
        "ref_code": "VP-037",
        "nombre": "DVH Alto Desempeño ST-120",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético con vidrio de control solar ST-120, equilibra transmisión de luz y control térmico para proyectos de alto desempeño.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-073.jpg",
        "categoria": "alto-desempeno",
        "activo": 1,
    },
    {
        "ref_code": "VP-038",
        "nombre": "DVH Alto Desempeño KNT-155",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético con vidrio KNT-155, alto desempeño térmico y acústico para fachadas exigentes.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-074.jpg",
        "categoria": "alto-desempeno",
        "activo": 1,
    },
    {
        "ref_code": "VP-039",
        "nombre": "DVH Confort Blanco",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono blanco, ideal para espacios luminosos que buscan confort térmico y acústico.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-075.jpg",
        "categoria": "confort",
        "activo": 1,
    },
    {
        "ref_code": "VP-040",
        "nombre": "DVH Confort Gris Asahi Pequeño",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono gris Asahi, combina elegancia y control de luminosidad.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-076.jpg",
        "categoria": "confort",
        "activo": 1,
    },
    {
        "ref_code": "VP-041",
        "nombre": "DVH Confort Incoloro",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético incoloro, para máxima transparencia sin sacrificar el confort térmico y acústico.",
        "especificaciones": "[completar]",
        "imagen_principal": "/static/img/vidrios/VP-077.jpg",
        "categoria": "confort",
        "activo": 1,
    },
]