# Exportado automaticamente desde la base de datos real.
# Total de vidrios encontrados: 41
#
# NOTA: Se modificaron los campos "imagen_principal" de los vidrios
# indicados por el cliente (colores: Azul Median Blue, Azul Oceano,
# Blanco, Incoloro, Naranja Tangerine, Rojo Dip, Violeta, Verde estructural,
# Verde esmeralda y Gris Asahi/Medium). Ademas, a esos mismos 25 productos
# se les agrego el campo "imagen_en_uso", que es la foto que se muestra
# en la seccion "En uso" del detalle de producto (la version con "HH"
# en el nombre del archivo). Los productos que NO tienen ese color
# confirmado no tienen este campo (queda ausente / None), y por lo tanto
# el script NO les crea ni modifica su producto_media.
#
# El resto de vidrios y todos los demas campos (nombre, descripcion,
# especificaciones, categoria, activo) quedan exactamente iguales al
# archivo original.
#
# Las imagenes correspondientes van dentro de la carpeta
# static/img/vidrios/ del proyecto, con esos nombres exactos
# (incluyendo espacios, tal como vienen del set de fotos Expocamacol).

VIDRIOS = [
    {
        "ref_code": "VP-001",
        "nombre": "DVH Confort Negro",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono negro, pensado para espacios de confort residencial con estética elegante y sobria.",
        "especificaciones": "Composición: 22.1/S10/5FT | Espesor: 19.3mm | Color: Negro | Separador: Swisspacer S10",
        "imagen_principal": "/static/img/vidrios/VP-037.jpg",
        "categoria": "confort",
        "activo": 1,
    },
    {
        "ref_code": "VP-002",
        "nombre": "DVH Confort Blanco",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono blanco, ideal para espacios luminosos que buscan confort térmico y acústico.",
        "especificaciones": "Composición: 44.1/S16/5FT | Espesor: 29.3mm | Color: Blanco | Separador: Swisspacer S16",
        "imagen_principal": "/static/img/vidrios/blanco%202.png",
        "imagen_en_uso": "/static/img/vidrios/blanco%201%20%20HH.png",
        "categoria": "confort",
        "activo": 1,
    },
    {
        "ref_code": "VP-003",
        "nombre": "DVH Confort Amarillo",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono amarillo, para proyectos que buscan un toque de color junto al aislamiento propio del DVH.",
        "especificaciones": "Composición: 44.1/S10/5FT | Espesor: 23.3mm | Color: Amarillo | Separador: Swisspacer S10",
        "imagen_principal": "/static/img/vidrios/VP-039.jpg",
        "categoria": "confort",
        "activo": 1,
    },
    {
        "ref_code": "VP-004",
        "nombre": "DVH Confort Azul Océano",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono azul océano, aporta frescura visual manteniendo el confort térmico del espacio.",
        "especificaciones": "Composición: 44.1/S10/5FT | Espesor: 23.3mm | Color: Azul Océano | Separador: Swisspacer S10",
        "imagen_principal": "/static/img/vidrios/azul%20ocean%202.png",
        "imagen_en_uso": "/static/img/vidrios/azul%20ocean%201%20HH.png",
        "categoria": "confort",
        "activo": 1,
    },
    {
        "ref_code": "VP-005",
        "nombre": "DVH Confort Median Blue",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono Median Blue, combina diseño contemporáneo con desempeño térmico.",
        "especificaciones": "Composición: 44.1/S12/5FT | Espesor: 25.3mm | Color: Median Blue | Separador: Swisspacer S12",
        "imagen_principal": "/static/img/vidrios/azul%20medium%202.png",
        "imagen_en_uso": "/static/img/vidrios/azul%20medium%201%20HH.png",
        "categoria": "confort",
        "activo": 1,
    },
    {
        "ref_code": "VP-006",
        "nombre": "DVH Arquitectonico Violeta",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono violeta, para fachadas y espacios con identidad visual distintiva.",
        "especificaciones": "Composición: 44.1/S16/5FT | Espesor: 29.3mm | Color: Violeta | Separador: Swisspacer S16",
        "imagen_principal": "/static/img/vidrios/violeta%201.png",
        "imagen_en_uso": "/static/img/vidrios/violeta%202%20HH.png",
        "categoria": "arquitectonico",
        "activo": 1,
    },
    {
        "ref_code": "VP-007",
        "nombre": "DVH Confort Gris Medium",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono gris Medium, aporta sobriedad y control de luminosidad manteniendo el confort térmico y acústico del espacio.",
        "especificaciones": "Composición: 44.1/S16/5FT | Espesor: 29.3mm | Color: Gris Medium | Separador: Swisspacer S16",
        "imagen_principal": "/static/img/vidrios/gris%20asahi%201.png",
        "imagen_en_uso": "/static/img/vidrios/gris%20asahi%202%20HH.png",
        "categoria": "confort",
        "activo": 1,
    },
    {
        "ref_code": "VP-008",
        "nombre": "DVH Confort Gris Asahi",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono gris Asahi, combina elegancia y control de luminosidad para espacios de confort residencial.",
        "especificaciones": "Composición: 44.1/S16/5FT | Espesor: 29.3mm | Color: Gris Asahi | Separador: Swisspacer S16",
        "imagen_principal": "/static/img/vidrios/gris%20asahi%201.png",
        "imagen_en_uso": "/static/img/vidrios/gris%20asahi%202%20HH.png",
        "categoria": "confort",
        "activo": 1,
    },
    {
        "ref_code": "VP-009",
        "nombre": "DVH Confort Gris Medium",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono gris Medium, aporta sobriedad y control de luminosidad sin sacrificar el confort térmico y acústico.",
        "especificaciones": "Composición: 44.1/S16/5FT | Espesor: 29.3mm | Color: Gris Medium | Separador: Swisspacer S16",
        "imagen_principal": "/static/img/vidrios/gris%20asahi%201.png",
        "imagen_en_uso": "/static/img/vidrios/gris%20asahi%202%20HH.png",
        "categoria": "confort",
        "activo": 1,
    },
    {
        "ref_code": "VP-010",
        "nombre": "DVH Arquitectonico Violeta",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono violeta, para fachadas y espacios con identidad visual distintiva.",
        "especificaciones": "Composición: 44.1/S16/5FT | Espesor: 29.3mm | Color: Violeta | Separador: Swisspacer S16",
        "imagen_principal": "/static/img/vidrios/violeta%201.png",
        "imagen_en_uso": "/static/img/vidrios/violeta%202%20HH.png",
        "categoria": "arquitectonico",
        "activo": 1,
    },
    {
        "ref_code": "VP-011",
        "nombre": "DVH Arquitectonico Verde",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono verde, aporta un aire natural al espacio sin perder desempeño térmico.",
        "especificaciones": "Composición: 44.1/S16/5FT | Espesor: 29.3mm | Color: Verde | Separador: Swisspacer S16",
        "imagen_principal": "/static/img/vidrios/verde%20dvh%20estructural%202.png",
        "imagen_en_uso": "/static/img/vidrios/verde%20dvh%20estructural%20%201%20HH.png",
        "categoria": "arquitectonico",
        "activo": 1,
    },
    {
        "ref_code": "VP-012",
        "nombre": "DVH Design Naranja Tangerine",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono naranja Tangerine, línea Design con acabado de alto impacto visual.",
        "especificaciones": "Composición: 44.1/S10/5FT | Espesor: 23.3mm | Color: Naranja Tangerine | Separador: Swisspacer S10",
        "imagen_principal": "/static/img/vidrios/naranja%20tangerin%202.png",
        "imagen_en_uso": "/static/img/vidrios/naranja%20tangerin%201%20HH.png",
        "categoria": "design",
        "activo": 1,
    },
    {
        "ref_code": "VP-013",
        "nombre": "DVH Confort SPVP Verde",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono verde con intercalar SPVP, combina estética natural y desempeño térmico para espacios de confort.",
        "especificaciones": "Composición: 44.5/S16/5FT | Espesor: 30.5mm | Color: Verde | Separador: Swisspacer S16",
        "imagen_principal": "/static/img/vidrios/verde%20esmeralda%201.jpeg",
        "imagen_en_uso": "/static/img/vidrios/verde%20esmeralda%202%20HH.jpeg",
        "categoria": "confort",
        "activo": 1,
    },
    {
        "ref_code": "VP-014",
        "nombre": "DVH Confort SPVP Verde",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono verde con intercalar SPVP, combina estética natural y desempeño térmico para espacios de confort.",
        "especificaciones": "Composición: 44.5/S16/5FT | Espesor: 30.5mm | Color: Verde | Separador: Swisspacer S16",
        "imagen_principal": "/static/img/vidrios/verde%20esmeralda%201.jpeg",
        "imagen_en_uso": "/static/img/vidrios/verde%20esmeralda%202%20HH.jpeg",
        "categoria": "confort",
        "activo": 1,
    },
    {
        "ref_code": "VP-015",
        "nombre": "DVH Confort Incoloro",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético incoloro, para máxima transparencia sin sacrificar el confort térmico y acústico.",
        "especificaciones": "Composición: 44.1/S16/5FT | Espesor: 29.3mm | Color: Incoloro | Separador: Swisspacer S16",
        "imagen_principal": "/static/img/vidrios/incoloro%202.png",
        "imagen_en_uso": "/static/img/vidrios/incoloro%201%20HH.png",
        "categoria": "confort",
        "activo": 1,
    },
    {
        "ref_code": "VP-016",
        "nombre": "DVH Confort Gris Median",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono gris Median, aporta sobriedad y control de luminosidad al espacio.",
        "especificaciones": "Composición: 44.1/S16/5FT | Espesor: 29.3mm | Color: Gris Median | Separador: Swisspacer S16",
        "imagen_principal": "/static/img/vidrios/gris%20asahi%201.png",
        "imagen_en_uso": "/static/img/vidrios/gris%20asahi%202%20HH.png",
        "categoria": "confort",
        "activo": 1,
    },
    {
        "ref_code": "VP-017",
        "nombre": "DVH Control Solar ST-150",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético con vidrio de control solar ST-150, ideal para fachadas con alta exposición solar.",
        "especificaciones": "Composición: 44.1/S16/5FT | Espesor: 29.3mm | Modelo: ST-150 | Separador: Swisspacer S16",
        "imagen_principal": "/static/img/vidrios/VP-053.jpg",
        "categoria": "control-solar",
        "activo": 1,
    },
    {
        "ref_code": "VP-018",
        "nombre": "DVH Control Solar STB-120",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético con vidrio de control solar STB-120, equilibra transmisión de luz y control térmico.",
        "especificaciones": "Composición: 44.1/S20/5FT | Espesor: 33.3mm | Modelo: STB-120 | Separador: Swisspacer S20",
        "imagen_principal": "/static/img/vidrios/VP-054.jpg",
        "categoria": "control-solar",
        "activo": 1,
    },
    {
        "ref_code": "VP-019",
        "nombre": "DVH Alto Desempeño KNT-155",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético con vidrio KNT-155, alto desempeño térmico y acústico para fachadas exigentes.",
        "especificaciones": "Composición: 44.1/S10/5FT | Espesor: 23.3mm | Modelo: KNT-155 | Separador: Swisspacer S10",
        "imagen_principal": "/static/img/vidrios/VP-055.jpg",
        "categoria": "alto-desempeno",
        "activo": 1,
    },
    {
        "ref_code": "VP-020",
        "nombre": "DVH Arquitectonico Verde",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono verde, aporta un aire natural al espacio sin perder desempeño térmico.",
        "especificaciones": "Composición: 44.1/S16/5FT | Espesor: 29.3mm | Color: Verde | Separador: Swisspacer S16",
        "imagen_principal": "/static/img/vidrios/verde%20dvh%20estructural%202.png",
        "imagen_en_uso": "/static/img/vidrios/verde%20dvh%20estructural%20%201%20HH.png",
        "categoria": "arquitectonico",
        "activo": 1,
    },
    {
        "ref_code": "VP-021",
        "nombre": "DVH Arquitectonico Rojo Dip",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono rojo Dip, para proyectos que buscan un acento de color audaz.",
        "especificaciones": "Composición: 44.1/S16/5FT | Espesor: 29.3mm | Color: Rojo Dip | Separador: Swisspacer S16",
        "imagen_principal": "/static/img/vidrios/rojo%20dip%201.png",
        "imagen_en_uso": "/static/img/vidrios/rojo%20dip%202%20HH.png",
        "categoria": "arquitectonico",
        "activo": 1,
    },
    {
        "ref_code": "VP-022",
        "nombre": "DVH Confort Bronce",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono bronce, aporta calidez y privacidad visual manteniendo el confort térmico y acústico del espacio.",
        "especificaciones": "Composición: 44.1/S16/5FT | Espesor: 29.3mm | Color: Bronce | Separador: Swisspacer S16",
        "imagen_principal": "/static/img/vidrios/VP-058.jpg",
        "categoria": "confort",
        "activo": 1,
    },
    {
        "ref_code": "VP-023",
        "nombre": "DVH Confort Gris Asahi",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono gris Asahi, combina elegancia y control de luminosidad.",
        "especificaciones": "Composición: 44.1/S16/5FT | Espesor: 29.3mm | Color: Gris Asahi | Separador: Swisspacer S16",
        "imagen_principal": "/static/img/vidrios/gris%20asahi%201.png",
        "imagen_en_uso": "/static/img/vidrios/gris%20asahi%202%20HH.png",
        "categoria": "confort",
        "activo": 1,
    },
    {
        "ref_code": "VP-024",
        "nombre": "DVH Confort Hielo",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono hielo, aporta luminosidad suave y estética contemporánea.",
        "especificaciones": "Composición: 44.1/S16/5FT | Espesor: 29.3mm | Color: Hielo | Separador: Swisspacer S16",
        "imagen_principal": "/static/img/vidrios/VP-060.jpg",
        "categoria": "confort",
        "activo": 1,
    },
    {
        "ref_code": "VP-025",
        "nombre": "DVH Control Solar ST-167",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético con vidrio de control solar ST-167, reduce la ganancia de calor solar manteniendo claridad.",
        "especificaciones": "Composición: 64.1/S16/5FT | Espesor: 31.3mm | Modelo: ST-167 | Separador: Swisspacer S16",
        "imagen_principal": "/static/img/vidrios/VP-061.jpg",
        "categoria": "control-solar",
        "activo": 1,
    },
    {
        "ref_code": "VP-026",
        "nombre": "DVH Control Solar ST-150 Grendo",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético con vidrio de control solar ST-150 Grendo, ideal para fachadas con alta exposición solar.",
        "especificaciones": "Composición: 44.1/S16/5FT | Espesor: 29.3mm | Modelo: ST-150 Grendo | Separador: Swisspacer S16",
        "imagen_principal": "/static/img/vidrios/VP-062.jpg",
        "categoria": "control-solar",
        "activo": 1,
    },
    {
        "ref_code": "VP-027",
        "nombre": "DVH Control Solar KNT-155",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético con vidrio de control solar KNT-155, alto desempeño térmico y acústico para fachadas exigentes.",
        "especificaciones": "Composición: 44.1/S10/5FT | Espesor: 23.3mm | Modelo: KNT-155 | Separador: Swisspacer S10",
        "imagen_principal": "/static/img/vidrios/VP-063.jpg",
        "categoria": "control-solar",
        "activo": 1,
    },
    {
        "ref_code": "VP-028",
        "nombre": "DVH Design Naranja Tangerine",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono naranja Tangerine, línea Design con acabado de alto impacto visual.",
        "especificaciones": "Composición: 44.1/S20/5FT | Espesor: 33.3mm | Color: Naranja Tangerine | Separador: Swisspacer S20",
        "imagen_principal": "/static/img/vidrios/naranja%20tangerin%202.png",
        "imagen_en_uso": "/static/img/vidrios/naranja%20tangerin%201%20HH.png",
        "categoria": "design",
        "activo": 1,
    },
    {
        "ref_code": "VP-029",
        "nombre": "DVH Control Solar ST-150",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético con vidrio de control solar ST-150, ideal para fachadas con alta exposición solar.",
        "especificaciones": "Composición: 44.1/S16/5FT | Espesor: 29.3mm | Modelo: ST-150 | Separador: Swisspacer S16",
        "imagen_principal": "/static/img/vidrios/VP-065.jpg",
        "categoria": "control-solar",
        "activo": 1,
    },
    {
        "ref_code": "VP-030",
        "nombre": "DVH Alto Desempeño ST-167",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético con vidrio de control solar ST-167, reduce la ganancia de calor solar manteniendo claridad y desempeño.",
        "especificaciones": "Composición: 44.1/S16/5FT | Espesor: 29.3mm | Modelo: ST-167 | Separador: Swisspacer S16",
        "imagen_principal": "/static/img/vidrios/VP-066.jpg",
        "categoria": "alto-desempeno",
        "activo": 1,
    },
    {
        "ref_code": "VP-031",
        "nombre": "DVH Arquitectonico Verde",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono verde, aporta un aire natural al espacio sin perder desempeño térmico.",
        "especificaciones": "Composición: 44.1/S16/5FT | Espesor: 29.3mm | Color: Verde | Separador: Swisspacer S16",
        "imagen_principal": "/static/img/vidrios/verde%20dvh%20estructural%202.png",
        "imagen_en_uso": "/static/img/vidrios/verde%20dvh%20estructural%20%201%20HH.png",
        "categoria": "arquitectonico",
        "activo": 1,
    },
    {
        "ref_code": "VP-032",
        "nombre": "DVH Control Solar ST-150",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético con vidrio de control solar ST-150, ideal para fachadas con alta exposición solar.",
        "especificaciones": "Composición: 44.1/S16/5FT | Espesor: 29.3mm | Modelo: ST-150 | Separador: Swisspacer S16",
        "imagen_principal": "/static/img/vidrios/VP-068.jpg",
        "categoria": "control-solar",
        "activo": 1,
    },
    {
        "ref_code": "VP-033",
        "nombre": "DVH Confort Blanco",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono blanco, ideal para espacios luminosos que buscan confort térmico y acústico.",
        "especificaciones": "Composición: 44.1/S16/5FT | Espesor: 29.3mm | Color: Blanco | Separador: Swisspacer S16",
        "imagen_principal": "/static/img/vidrios/blanco%202.png",
        "imagen_en_uso": "/static/img/vidrios/blanco%201%20%20HH.png",
        "categoria": "confort",
        "activo": 1,
    },
    {
        "ref_code": "VP-034",
        "nombre": "DVH Arquitectonico Rojo Dip",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono rojo Dip, para proyectos que buscan un acento de color audaz.",
        "especificaciones": "Composición: 44.1/S16/5FT | Espesor: 29.3mm | Color: Rojo Dip | Separador: Swisspacer S16",
        "imagen_principal": "/static/img/vidrios/rojo%20dip%201.png",
        "imagen_en_uso": "/static/img/vidrios/rojo%20dip%202%20HH.png",
        "categoria": "arquitectonico",
        "activo": 1,
    },
    {
        "ref_code": "VP-035",
        "nombre": "DVH Confort Azul Median Blue",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono azul Median Blue, combina diseño contemporáneo con desempeño térmico.",
        "especificaciones": "Composición: 44.1/S12/5FT | Espesor: 25.3mm | Color: Median Blue | Separador: Swisspacer S12",
        "imagen_principal": "/static/img/vidrios/azul%20medium%202.png",
        "imagen_en_uso": "/static/img/vidrios/azul%20medium%201%20HH.png",
        "categoria": "confort",
        "activo": 1,
    },
    {
        "ref_code": "VP-036",
        "nombre": "DVH Control Solar ST-120",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético con vidrio de control solar ST-120, equilibra transmisión de luz y control térmico.",
        "especificaciones": "Composición: 44.1/S10/5FT | Espesor: 23.3mm | Modelo: ST-120 | Separador: Swisspacer S10",
        "imagen_principal": "/static/img/vidrios/VP-072.jpg",
        "categoria": "control-solar",
        "activo": 1,
    },
    {
        "ref_code": "VP-037",
        "nombre": "DVH Alto Desempeño ST-120",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético con vidrio de control solar ST-120, equilibra transmisión de luz y control térmico para proyectos de alto desempeño.",
        "especificaciones": "Composición: 44.1/S16/5FT | Espesor: 29.3mm | Modelo: ST-120 | Separador: Swisspacer S16",
        "imagen_principal": "/static/img/vidrios/VP-073.jpg",
        "categoria": "alto-desempeno",
        "activo": 1,
    },
    {
        "ref_code": "VP-038",
        "nombre": "DVH Alto Desempeño KNT-155",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético con vidrio KNT-155, alto desempeño térmico y acústico para fachadas exigentes.",
        "especificaciones": "Composición: 44.1/S16/5FT | Espesor: 29.3mm | Modelo: KNT-155 | Separador: Swisspacer S16",
        "imagen_principal": "/static/img/vidrios/VP-074.jpg",
        "categoria": "alto-desempeno",
        "activo": 1,
    },
    {
        "ref_code": "VP-039",
        "nombre": "DVH Confort Blanco",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono blanco, ideal para espacios luminosos que buscan confort térmico y acústico.",
        "especificaciones": "Composición: 44.1/S16/5FT | Espesor: 29.3mm | Color: Blanco | Separador: Swisspacer S16",
        "imagen_principal": "/static/img/vidrios/blanco%202.png",
        "imagen_en_uso": "/static/img/vidrios/blanco%201%20%20HH.png",
        "categoria": "confort",
        "activo": 1,
    },
    {
        "ref_code": "VP-040",
        "nombre": "DVH Confort Gris Asahi Pequeño",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético en tono gris Asahi, combina elegancia y control de luminosidad.",
        "especificaciones": "Composición: 44.1/S16/5FT | Espesor: 29.3mm | Color: Gris Asahi | Separador: Swisspacer S16",
        "imagen_principal": "/static/img/vidrios/gris%20asahi%201.png",
        "imagen_en_uso": "/static/img/vidrios/gris%20asahi%202%20HH.png",
        "categoria": "confort",
        "activo": 1,
    },
    {
        "ref_code": "VP-041",
        "nombre": "DVH Confort Incoloro",
        "tipo_vidrio": "DVH",
        "descripcion": "Doble vidriado hermético incoloro, para máxima transparencia sin sacrificar el confort térmico y acústico.",
        "especificaciones": "Composición: 44.1/S16/5FT | Espesor: 29.3mm | Color: Incoloro | Separador: Swisspacer S16",
        "imagen_principal": "/static/img/vidrios/incoloro%202.png",
        "imagen_en_uso": "/static/img/vidrios/incoloro%201%20HH.png",
        "categoria": "confort",
        "activo": 1,
    },
]